# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weight_record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='weight_record.proto',
  package='parameters',
  syntax='proto3',
  serialized_pb=_b('\n\x13weight_record.proto\x12\nparameters\"@\n\x0bModelRecord\x12\x0c\n\x04loss\x18\x01 \x01(\x02\x12#\n\x07weights\x18\x02 \x03(\x0b\x32\x12.parameters.Neuron\"\x18\n\x06Neuron\x12\x0e\n\x06weight\x18\x01 \x03(\x02\x62\x06proto3')
)




_MODELRECORD = _descriptor.Descriptor(
  name='ModelRecord',
  full_name='parameters.ModelRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loss', full_name='parameters.ModelRecord.loss', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weights', full_name='parameters.ModelRecord.weights', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=99,
)


_NEURON = _descriptor.Descriptor(
  name='Neuron',
  full_name='parameters.Neuron',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='parameters.Neuron.weight', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=125,
)

_MODELRECORD.fields_by_name['weights'].message_type = _NEURON
DESCRIPTOR.message_types_by_name['ModelRecord'] = _MODELRECORD
DESCRIPTOR.message_types_by_name['Neuron'] = _NEURON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelRecord = _reflection.GeneratedProtocolMessageType('ModelRecord', (_message.Message,), dict(
  DESCRIPTOR = _MODELRECORD,
  __module__ = 'weight_record_pb2'
  # @@protoc_insertion_point(class_scope:parameters.ModelRecord)
  ))
_sym_db.RegisterMessage(ModelRecord)

Neuron = _reflection.GeneratedProtocolMessageType('Neuron', (_message.Message,), dict(
  DESCRIPTOR = _NEURON,
  __module__ = 'weight_record_pb2'
  # @@protoc_insertion_point(class_scope:parameters.Neuron)
  ))
_sym_db.RegisterMessage(Neuron)


# @@protoc_insertion_point(module_scope)
